export const USER_CHANGE = 'USER_CHANGE';
export const SNACKBAR_CHANGE = 'SNACKBAR_CHANGE';
export const VALIDATION_CHANGE = 'VALIDATION_CHANGE';
export const DRAWER_CHANGE = 'DRAWER_CHANGE';
export const AUTH_CHANGE = 'AUTH_CHANGE';
